---
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  RpHaven\Protobuf\:
    resource: '../src/'

  RpHaven\Protobuf\Grpc\Hydration\Uid\GrpcUidFactory: '@RpHaven\Protobuf\Grpc\Hydration\Uid\ChainFactoryFactoryGrpc'

  RpHaven\Protobuf\Grpc\Hydration\Uid\ChainFactoryFactoryGrpc:
    factory: [null, 'init']

